openapi: 3.0.0
info:
  title: Image comparison API
  version: 1.0.0
paths:
  /upload:
    post:
      summary: Upload and compare two images
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image1:
                  type: string
                  format: binary
                image2:
                  type: string
                  format: binary
      responses:
        '200':
          description: Images are equal, returned overlaid pictures
          content:
            image/png:
              schema:
                type: string
                format: binary
        '400':
          description: Images have difference, returned overlaid pictures with colored pixels
          content:
            image/png:
              schema:
                type: string
                format: binary
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string