@startuml


left to right direction

package "Server" {

  [Facade] 
  [API Gateway]
  [Rendering Service]
  [Core]
  [Comparison Service]
  [Reporting Service]
  [Facade] --> [API Gateway]
  [API Gateway] --> [Rendering Service]
  [API Gateway] -> [Core]
  [API Gateway] --> [Comparison Service]
  [API Gateway] --> [Reporting Service]
  [API Gateway] --> Database

  note right of Core: business logic

  database "Database" {

  }
}

component Client {
  port TestingTool
  port BrowserExtension
}

[Facade] --> TestingTool
[Facade] --> BrowserExtension
[Facade] --> [User Interface]

@enduml

